name: atc_drive
description: "ATC Drive"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  intl: ^0.20.1
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.4.0
  dio: ^5.7.0
  get_storage: ^2.1.1
  uuid: ^4.5.1
  http: ^1.3.0
  file_picker: ^9.0.2
  permission_handler: ^11.4.0
  share_plus: ^10.1.4
  open_filex: ^4.7.0
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/png/
